services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5050:5050
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
