services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # environment:
    #   - MONGO_URI=mongodb://mongo-db:27017/web-server
    ports:
      - 8080:8080
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
